name: Build Prod Site

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build, tag, and push image to Amazon ECR
        env:
          AWS_DEFAULT_REGION: us-east-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install
          docker login -u AWS -p $(aws ecr-public get-login-password) public.ecr.aws/w5f9v2w7
          docker build -t ddns .
          docker tag ddns:latest public.ecr.aws/w5f9v2w7/ddns:latest
          docker push public.ecr.aws/w5f9v2w7/ddns:latest
