name: Build Prod Site

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build, tag, and push image to Amazon ECR
        env:
          AWS_DEFAULT_REGION: us-east-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          sudo apt-get update -y
          sudo apt-get install -y python3-setuptools python3-pip
          sudo pip3 install awscli --upgrade --user
          aws ecr-public get-login-password | docker login --username AWS --password-stdin public.ecr.aws/w5f9v2w7
          docker build -t ddns .
          docker tag ddns:latest public.ecr.aws/w5f9v2w7/ddns:latest
          docker push public.ecr.aws/w5f9v2w7/ddns:latest
